In [ ]:
import numpy as np #Импортируем библиотеку Numpy
my_array = np.arange(5, 101, 5) # создаём массив
my_array #вывод массива

In [2]:
my_array_10 = my_array[my_array % 10 == 0] #Массив кратный 10 из массива my_array
my_array_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [13]:
my_array_2d = my_array.reshape(-1, 2) # Создаём 2-мерный массив
my_array_2d


array([[  5,  10],
       [ 15,  20],
       [ 25,  30],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100]])

In [14]:
my_second_array = my_array - 5 #создаём второй массив с значения меньшими на 5 от my_arrray
my_second_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
# Преобразуем массив my_second_array в двумерный и транспонируем
my_second_array_2d = my_second_array.reshape(-1, 2)
# Объединяем my_2d_array.T и my_second_array_2d по горизонтали
combined_array = np.hstack((my_array_2d.T, my_second_array_2d.T))
combined_array


array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95,   0,  10,  20,
         30,  40,  50,  60,  70,  80,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,   5,  15,  25,
         35,  45,  55,  65,  75,  85,  95]])

In [29]:
# Выделяем 4 верхние строки
top_rows = my_array_2d[:4]

# Выделяем 2 и 3 строки
rows_to_divide = my_array_2d[1:3]  # это строки 1 и 2 (второй и третий элементы)

# Делим 2-ю строку на 1-ю, 3-ю на 2-ю
result = np.empty_like(rows_to_divide, dtype=float)
result[0] = rows_to_divide[0] / top_rows[0]  # 2-я строка / 1-я
result[1] = rows_to_divide[1] / top_rows[1]  # 3-я строка / 2-я

# Транспонируем результат
result_transposed = result.T

print("Результат деления и транспонирования:")
print(result_transposed)


Результат деления и транспонирования:
[[3.         1.66666667]
 [2.         1.5       ]]


In [30]:
# Сравниваем результаты с исходными строками
unchanged_values = np.where(result == rows_to_divide, result, np.nan)  # Заменяем изменённые значения на NaN

# Удаляем NaN из результата
unchanged_values = unchanged_values[~np.isnan(unchanged_values)]
print("Оставленные значения, которые не изменились после деления:")
print(unchanged_values)

Оставленные значения, которые не изменились после деления:
[]


In [32]:
# Получаем трехстрочный массив (добавляем одну строку, чтобы получить 3)
three_row_array = np.vstack((top_rows[:2], result))  # Выбираем 2 верхние строки и добавляем результат

# Меняем местами первую и третью строки
three_row_array[[0, 2]] = three_row_array[[2, 0]]

three_row_array

array([[ 3.        ,  2.        ],
       [15.        , 20.        ],
       [ 5.        , 10.        ],
       [ 1.66666667,  1.5       ]])

In [34]:
# Вычисляем среднее, медиану и стандартное отклонение для каждой строки
mean_values = np.mean(three_row_array, axis=1)
median_values = np.median(three_row_array, axis=1)
std_values = np.std(three_row_array, axis=1)
mean_values
median_values
std_values

array([0.5       , 2.5       , 2.5       , 0.08333333])

In [35]:
# Нормализация на максимальное значение вдоль строк
max_values = np.max(three_row_array, axis=1, keepdims=True)  # Получаем максимальные значения с сохранением размерности
normalized_array = three_row_array / max_values  # Делим каждый элемент на максимальное значение
normalized_array

array([[1.        , 0.66666667],
       [0.75      , 1.        ],
       [0.5       , 1.        ],
       [1.        , 0.9       ]])

In [36]:
import pandas as pd #Импортируем pandas
df = pd.read_csv('Global Population Trends(2016-2022).csv') # Импортируем данные из файла Global Population Trends(2016-2022).csv
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

In [37]:
df.head() # выводим несколько первых строк

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

In [39]:
df.shape #Определяем размерность фрейма

(1073, 12)

In [40]:
df.columns #Выводим название заголовков столбцов

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [41]:
df.info #Получаем описание всех переменных(полей)

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

In [43]:
df1=df[df['Total Population']!='-'] #Удаляем строки не содержащие значение в столбце Total Population
df1


Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

In [45]:
df.describe() #Получаем описательную информацию

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

In [48]:
df2 = df.sort_values(by = 'Year', ascending=False) #Сортируем по годам
df.head()

Country  Year Total Population Urban Population Rural Population  \
425    Hungary  2021        9,709,891        7,014,911        2,694,980   
420  Hong Kong  2021        7,413,100        7,413,100                -   
445       Iran  2021       87,923,432       67,125,144       20,798,288   
440  Indonesia  2021      273,753,191      156,833,203      116,919,988   
435      India  2021    1,407,563,842      498,179,071      909,384,771   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
425                  -              74       9.700      16.100           1.59   
420                  -              85       5.000       6.900          0.772   
445                  -              74      13.699       6.437          1.692   
440                  -              68      16.425      10.065          2.175   
435                  -              67      16.419       9.448          2.031   

    Infant Mortality Rate Growth Rate  
425                   3.3           0  
420                     -          -1  
445                  10.9           1  
440                  18.9           1  
435                  25.5           1

In [49]:
max_population_country = df.loc[df['Total Population'].idxmax(), 'Country'] #Выводим страну с самым большим колиеством жителей
max_population_country

'Seychelles'

In [51]:
min_population_country = df.loc[df['Total Population'].idxmin(), 'Country']#Выводим страну с самым меньшим колиеством жителей
min_population_country

'Albania'

In [52]:
df.to_excel(r'D:\Projects\Big_Data_5_semester\GPT(2016-2022)_excel_version.xlsx') #Экспортируем фрейм в Excel